#!/usr/bin/env python3
import argparse
import os

import cynthia.databases as db

parser = argparse.ArgumentParser(description='Automated Testing for ORM Systems')
parser.add_argument('--schemas', '-s', type=str,
                    required=True,
                    help='Path to input database schemas')

DB_USER = 'orm_testing'
DB_PASS = 'orm_testing'


def main():
    args = parser.parse_args()

    if not os.path.isdir(args.schemas):
        print ("'{}' is not a directory".format(args.schemas))
        exit(1)

    print ('Setting up Database Schemas {}'.format(args.schemas))
    for schema in os.listdir(args.schemas):
        if not schema.endswith('.sql'):
            continue
        print ('Processing {}...'.format(schema))
        dbname, _ = schema.split('.sql')
        for DBClass in [db.MySQL, db.Postgres, db.SQLite3]:
            dbobj = DBClass(dbname, user=DB_USER, password=DB_PASS)
            dbobj.createdb()
            dbobj.setupSchema(schema)
    exit(0)

if __name__ == '__main__':
    main()
